# Site settings
title: 
header-img: img/home-bg.png
email: lmchambers0420@gmail.com
copyright_name: unikornintech
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: unikornintech
github_username:  unikornintech
learn_profile: unikornintech
email_username: lmchambers0420@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
